# Generated by Django 3.0.3 on 2020-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wav_file_links', models.TextField()),
                ('Auto_Transcribed_Text', models.TextField()),
            ],
        ),
    ]
