# Generated by Django 3.0.3 on 2020-04-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransWalk',
            fields=[
                ('ASRid', models.AutoField(primary_key=True, serialize=False)),
                ('Audio_File_Link', models.CharField(blank=True, help_text='Audio Links', max_length=200, null=True)),
                ('audio_duration', models.BigIntegerField(blank=True, null=True)),
                ('ASR_text', models.TextField(blank=True, help_text='ASR Output', null=True)),
                ('Transcripted_Text', models.TextField(blank=True, help_text='Most Recent Transcripted Text', null=True)),
                ('IsOpenFlag', models.BooleanField(blank=True, default=False, null=True)),
                ('Updated_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('Trans_Counter', models.IntegerField(blank=True, default=0, null=True)),
                ('Transcribers_Checked', models.CharField(blank=True, help_text='Usernames of the transcribers Who checked the specific audio', max_length=200, null=True)),
                ('click_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('caller_phone_number', models.CharField(blank=True, help_text='Caller Phone Nyumber', max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='audio_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio_info',
            name='Auto_Transcribed_Text',
            field=models.TextField(help_text='Auto Transcribed Text From The ASR'),
        ),
        migrations.AlterField(
            model_name='audio_info',
            name='wav_file_links',
            field=models.CharField(help_text='Audio Links', max_length=200),
        ),
        migrations.CreateModel(
            name='TransIndiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_link', models.CharField(blank=True, help_text='Audio Links', max_length=200, null=True)),
                ('Text_Indiv', models.TextField(blank=True, null=True)),
                ('audio_duration', models.BigIntegerField(blank=True, null=True)),
                ('counter_left', models.IntegerField(blank=True, null=True)),
                ('Transcribed_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('Transcribed_By', models.CharField(blank=True, max_length=50, null=True)),
                ('asrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TransWalk')),
            ],
        ),
    ]
