# Generated by Django 3.0.3 on 2020-02-20 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200220_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 1, 15, 343141)),
        ),
    ]
