# Generated by Django 3.0.3 on 2020-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_audio_info_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio_info',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='audio_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
