# Generated by Django 3.0.3 on 2020-03-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200220_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio_info',
            options={},
        ),
    ]
