# Generated by Django 3.0.3 on 2020-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transwalk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transwalk',
            name='Transcribers_Checked',
            field=models.CharField(blank=True, help_text='Usernames of the transcribers Who checked the specific audio', max_length=200, null=True),
        ),
    ]
