# Generated by Django 3.0.3 on 2020-03-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200311_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transwalk',
            name='IsOpenFlag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
