# Generated by Django 3.0.3 on 2020-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200311_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transwalk',
            name='IsOpenFlag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transwalk',
            name='Updated_At',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
