# Generated by Django 3.0.3 on 2020-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200311_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transwalk',
            name='Trans_Counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
