# Generated by Django 3.0.3 on 2020-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200311_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transwalk',
            name='IsOpenFlag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
