# Generated by Django 3.0.3 on 2020-03-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200311_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransIndiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text_Indiv', models.TextField()),
                ('Transcribed_At', models.DateTimeField(auto_now_add=True)),
                ('Transcribed_By', models.CharField(max_length=50)),
                ('ASRid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TransWalk')),
            ],
        ),
    ]
