# Generated by Django 3.0.3 on 2020-03-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_transindiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='transindiv',
            name='audio_file_link',
            field=models.CharField(default=None, help_text='Audio Links', max_length=200),
            preserve_default=False,
        ),
    ]
