# Generated by Django 3.0.3 on 2020-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_transindiv_audio_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='transwalk',
            name='ASR_text',
            field=models.TextField(blank=True, help_text='ASR Output', null=True),
        ),
    ]
