# Generated by Django 3.0.3 on 2020-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_transwalk_asr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='transwalk',
            name='audio_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
