# Generated by Django 3.0.3 on 2020-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_transwalk_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='transindiv',
            name='audio_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
