# Generated by Django 3.0.3 on 2020-03-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_transindiv_audio_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transindiv',
            old_name='ASRid',
            new_name='asrid',
        ),
    ]
