# Generated by Django 3.0.3 on 2020-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_transindiv_counter_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='transwalk',
            name='click_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
