# Generated by Django 3.0.3 on 2020-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_transwalk_click_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transindiv',
            name='Transcribed_At',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transindiv',
            name='Transcribed_By',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
