# Generated by Django 3.0.3 on 2020-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200412_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='transwalk',
            name='caller_phone_number',
            field=models.CharField(blank=True, help_text='Caller Phone Nyumber', max_length=15, null=True),
        ),
    ]
