# Generated by Django 3.0.3 on 2020-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_transwalk_caller_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transindiv',
            name='audio_file_link',
            field=models.CharField(blank=True, help_text='Audio Links', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transwalk',
            name='Audio_File_Link',
            field=models.CharField(blank=True, help_text='Audio Links', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transwalk',
            name='Transcripted_Text',
            field=models.TextField(blank=True, help_text='Most Recent Transcripted Text', null=True),
        ),
    ]
